"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";

type CalendarItem={_id:string;title:string;type:string;startsAt:string;endsAt?:string|null;timezone:string;notes:string};
type ProjectItem={_id:string;title:string;status:string;hypothesis:string;methodology:string;notes:string;isPublic:boolean;updatedAt:string};
type WritingItem={_id:string;title:string;type:string;status:string;sections:Record<string,string>;versions:Array<{content:string;createdAt:string}>;updatedAt:string};
type InterviewItem={_id:string;title:string;researchDiscussionNotes:string;universityNotes:string;checklist:string[];questions:string[];mockAnswers:string[];updatedAt:string};
type Tab="calendar"|"projects"|"writing"|"interview";

async function request(url:string,init?:RequestInit){const response=await fetch(url,{cache:"no-store",...init});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message??"Request failed.");return body.data;}
const splitLines=(value:FormDataEntryValue|null)=>String(value??"").split(/\r?\n/).map((item)=>item.trim()).filter(Boolean);

export function ResearchWorkspace(){
  const [tab,setTab]=useState<Tab>("calendar");
  const [calendar,setCalendar]=useState<CalendarItem[]>([]);const [projects,setProjects]=useState<ProjectItem[]>([]);const [writing,setWriting]=useState<WritingItem[]>([]);const [interviews,setInterviews]=useState<InterviewItem[]>([]);
  const [busy,setBusy]=useState(false);const [status,setStatus]=useState("");
  const refresh=useCallback(async()=>{try{const [c,p,w,i]=await Promise.all([request("/api/v1/me/calendar"),request("/api/v1/me/projects"),request("/api/v1/me/writing-workspaces"),request("/api/v1/me/interview-prep")]);setCalendar(c.items as CalendarItem[]);setProjects(p.items as ProjectItem[]);setWriting(w.items as WritingItem[]);setInterviews(i.items as InterviewItem[]);}catch(error){setStatus(error instanceof Error?error.message:"Could not load research workspace.");}},[]);
  useEffect(()=>{void refresh();},[refresh]);
  async function submit(url:string,payload:Record<string,unknown>,success:string){setBusy(true);setStatus("");try{await request(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});await refresh();setStatus(success);}catch(error){setStatus(error instanceof Error?error.message:"Request failed.");}finally{setBusy(false);}}
  async function remove(url:string,success:string){setBusy(true);try{await request(url,{method:"DELETE"});await refresh();setStatus(success);}catch(error){setStatus(error instanceof Error?error.message:"Delete failed.");}finally{setBusy(false);}}
  function createCalendar(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const startsAt=String(f.get("startsAt")??"");if(!startsAt)return;void submit("/api/v1/me/calendar",{title:String(f.get("title")??""),type:String(f.get("type")??"TASK"),startsAt:new Date(startsAt).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",sourceType:"MANUAL",sourceId:null,notes:String(f.get("notes")??""),reminderMinutes:[1440]},"Calendar item created.");event.currentTarget.reset();}
  function createProject(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);void submit("/api/v1/me/projects",{title:String(f.get("title")??""),hypothesis:String(f.get("hypothesis")??""),methodology:String(f.get("methodology")??""),notes:String(f.get("notes")??""),references:splitLines(f.get("references")),collaboratorNames:[],documentIds:[],milestones:[],status:"IDEA",isPublic:false},"Research project created.");event.currentTarget.reset();}
  function createWriting(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);void submit("/api/v1/me/writing-workspaces",{type:String(f.get("type")??"SOP"),title:String(f.get("title")??""),universityId:null,sections:{opening:String(f.get("opening")??"")},citationPlaceholders:[],status:"DRAFT"},"Writing workspace created.");event.currentTarget.reset();}
  function createInterview(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);void submit("/api/v1/me/interview-prep",{title:String(f.get("title")??""),professorId:null,universityId:null,applicationId:null,researchDiscussionNotes:String(f.get("researchNotes")??""),universityNotes:String(f.get("universityNotes")??""),checklist:splitLines(f.get("checklist")),questions:splitLines(f.get("questions")),mockAnswers:[]},"Interview preparation workspace created.");event.currentTarget.reset();}
  const tabs:Array<[Tab,string]>=[["calendar","Academic calendar"],["projects","Research projects"],["writing","SOP & proposal"],["interview","Interview prep"]];
  return <div className="space-y-6"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Research workspace modules">{tabs.map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)} className={`rounded-md px-3 py-2 text-sm font-medium ${tab===value?"bg-slate-950 text-white":"border bg-white text-slate-700"}`}>{label}</button>)}</div>
    {tab==="calendar"?<section className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Academic calendar</h2><p className="text-sm text-slate-600">Track deadlines, interviews, follow-ups, meetings and tasks.</p></div><a href="/api/v1/me/calendar/export" className="rounded-md border bg-white px-3 py-2 text-sm font-medium">Export .ics</a></div><form onSubmit={createCalendar} className="grid gap-3 rounded-xl border bg-white p-5 md:grid-cols-2"><input required name="title" placeholder="Event title" className="rounded-md border px-3 py-2 text-sm"/><select name="type" className="rounded-md border px-3 py-2 text-sm"><option value="DEADLINE">Deadline</option><option value="INTERVIEW">Interview</option><option value="FOLLOW_UP">Follow-up</option><option value="TASK">Task</option><option value="MEETING">Meeting</option><option value="OTHER">Other</option></select><input required name="startsAt" type="datetime-local" className="rounded-md border px-3 py-2 text-sm"/><input name="notes" placeholder="Notes" className="rounded-md border px-3 py-2 text-sm"/><button disabled={busy} className="w-fit rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Add event</button></form><div className="space-y-3">{calendar.map(item=><article key={item._id} className="rounded-xl border bg-white p-4"><div className="flex justify-between gap-3"><div><p className="text-xs font-medium text-slate-500">{item.type}</p><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-slate-600">{new Date(item.startsAt).toLocaleString()} · {item.timezone}</p>{item.notes?<p className="mt-2 text-sm text-slate-600">{item.notes}</p>:null}</div><button disabled={busy} onClick={()=>remove(`/api/v1/me/calendar/${encodeURIComponent(item._id)}`,"Calendar item deleted.")} className="h-fit rounded-md border px-2 py-1 text-xs text-red-700">Delete</button></div></article>)}{calendar.length===0?<p className="text-sm text-slate-600">No calendar events yet.</p>:null}</div></section>:null}
    {tab==="projects"?<section className="space-y-5"><div><h2 className="text-lg font-semibold">Research projects</h2><p className="text-sm text-slate-600">Keep hypotheses, methodology, references and project notes organized.</p></div><form onSubmit={createProject} className="grid gap-3 rounded-xl border bg-white p-5"><input required name="title" placeholder="Project title" className="rounded-md border px-3 py-2 text-sm"/><textarea name="hypothesis" placeholder="Hypothesis / research question" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><textarea name="methodology" placeholder="Methodology" className="min-h-24 rounded-md border px-3 py-2 text-sm"/><textarea name="notes" placeholder="Notes" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><textarea name="references" placeholder="References or URLs, one per line" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><button disabled={busy} className="w-fit rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Create project</button></form><div className="grid gap-4 lg:grid-cols-2">{projects.map(item=><article key={item._id} className="rounded-xl border bg-white p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-medium text-slate-500">{item.status} · {item.isPublic?"Public":"Private"}</p><h3 className="mt-1 font-semibold">{item.title}</h3></div><button disabled={busy} onClick={()=>remove(`/api/v1/me/projects/${encodeURIComponent(item._id)}`,"Project deleted.")} className="h-fit rounded-md border px-2 py-1 text-xs text-red-700">Delete</button></div>{item.hypothesis?<p className="mt-3 text-sm text-slate-600"><strong>Hypothesis:</strong> {item.hypothesis}</p>:null}{item.methodology?<p className="mt-2 text-sm text-slate-600"><strong>Method:</strong> {item.methodology}</p>:null}</article>)}{projects.length===0?<p className="text-sm text-slate-600">No research projects yet.</p>:null}</div></section>:null}
    {tab==="writing"?<section className="space-y-5"><div><h2 className="text-lg font-semibold">SOP & research proposal workspace</h2><p className="text-sm text-slate-600">Create factual drafts with version-ready storage. Verify every citation and claim before submission.</p></div><form onSubmit={createWriting} className="grid gap-3 rounded-xl border bg-white p-5"><div className="grid gap-3 md:grid-cols-2"><select name="type" className="rounded-md border px-3 py-2 text-sm"><option value="SOP">Statement of Purpose</option><option value="RESEARCH_PROPOSAL">Research Proposal</option></select><input required name="title" placeholder="Workspace title" className="rounded-md border px-3 py-2 text-sm"/></div><textarea name="opening" placeholder="Opening notes / initial section" className="min-h-32 rounded-md border px-3 py-2 text-sm"/><button disabled={busy} className="w-fit rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Create writing workspace</button></form><div className="grid gap-4 lg:grid-cols-2">{writing.map(item=><article key={item._id} className="rounded-xl border bg-white p-5"><p className="text-xs font-medium text-slate-500">{item.type.replaceAll("_"," ")} · {item.status}</p><h3 className="mt-1 font-semibold">{item.title}</h3><p className="mt-3 text-sm text-slate-600">{Object.keys(item.sections??{}).length} structured section(s) · {item.versions?.length??0} saved version(s)</p></article>)}{writing.length===0?<p className="text-sm text-slate-600">No writing workspaces yet.</p>:null}</div></section>:null}
    {tab==="interview"?<section className="space-y-5"><div><h2 className="text-lg font-semibold">Interview preparation</h2><p className="text-sm text-slate-600">Prepare research discussion points, university notes, questions and a checklist.</p></div><form onSubmit={createInterview} className="grid gap-3 rounded-xl border bg-white p-5"><input required name="title" placeholder="Interview / meeting title" className="rounded-md border px-3 py-2 text-sm"/><textarea name="researchNotes" placeholder="Research discussion notes" className="min-h-24 rounded-md border px-3 py-2 text-sm"/><textarea name="universityNotes" placeholder="University / lab notes" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><textarea name="questions" placeholder="Questions to ask, one per line" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><textarea name="checklist" placeholder="Preparation checklist, one per line" className="min-h-20 rounded-md border px-3 py-2 text-sm"/><button disabled={busy} className="w-fit rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Create interview prep</button></form><div className="grid gap-4 lg:grid-cols-2">{interviews.map(item=><article key={item._id} className="rounded-xl border bg-white p-5"><h3 className="font-semibold">{item.title}</h3>{item.researchDiscussionNotes?<p className="mt-3 text-sm text-slate-600">{item.researchDiscussionNotes}</p>:null}<p className="mt-3 text-xs text-slate-500">{item.questions.length} question(s) · {item.checklist.length} checklist item(s)</p></article>)}{interviews.length===0?<p className="text-sm text-slate-600">No interview preparation workspaces yet.</p>:null}</div></section>:null}
    {status?<p role="status" className="rounded-lg border bg-slate-50 px-4 py-3 text-sm text-slate-700">{status}</p>:null}</div>;
}
