import Link from "next/link";
import { DeadlineBadge } from "@/components/discovery/DeadlineBadge";
import { opportunitySearchSchema } from "@/schemas/opportunities";
import { searchOpportunities, type DeadlineState } from "@/server/opportunities/opportunity.service";

export const metadata = { title: "Opportunities | ResearVia" };
const types = ["PHD","MASTERS","RESEARCH_ASSISTANT","TEACHING_ASSISTANT","RESEARCH_INTERNSHIP","INDUSTRY_RESEARCH_INTERNSHIP","FELLOWSHIP","CONFERENCE","WORKSHOP","SUMMER_PROGRAM","RESEARCH_PROJECT","OTHER"];

function pageHref(page: number, query: { q: string; country: string; researchArea: string; type: string; openOnly: boolean }) { const params=new URLSearchParams(); if(query.q)params.set("q",query.q); if(query.country)params.set("country",query.country); if(query.researchArea)params.set("researchArea",query.researchArea); if(query.type)params.set("type",query.type); if(query.openOnly)params.set("openOnly","true"); params.set("page",String(page)); return `/dashboard/opportunities?${params.toString()}`; }

export default async function OpportunitiesPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) { const raw=await searchParams; const parsed=opportunitySearchSchema.safeParse({q:typeof raw.q==="string"?raw.q:"",country:typeof raw.country==="string"?raw.country:"",researchArea:typeof raw.researchArea==="string"?raw.researchArea:"",type:typeof raw.type==="string"?raw.type:"",openOnly:raw.openOnly==="true"?"true":"false",page:typeof raw.page==="string"?raw.page:1,limit:20}); const query=parsed.success?parsed.data:{q:"",country:"",researchArea:"",type:"" as const,openOnly:false,page:1,limit:20}; const result=await searchOpportunities(query); return <div className="mx-auto max-w-6xl"><div className="border-b border-slate-200 pb-6"><p className="text-sm font-medium text-slate-500">Academic opportunities</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Opportunities</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">PhD positions, research roles, internships, fellowships and academic programs from published source-backed records.</p></div>
<form className="mt-6 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm lg:grid-cols-[1fr_170px_200px_210px_auto]"><input name="q" defaultValue={query.q} placeholder="Title or organization" className="h-10 rounded-lg border border-slate-200 px-3 text-sm"/><input name="country" defaultValue={query.country} placeholder="Country" className="h-10 rounded-lg border border-slate-200 px-3 text-sm"/><input name="researchArea" defaultValue={query.researchArea} placeholder="Research area" className="h-10 rounded-lg border border-slate-200 px-3 text-sm"/><select name="type" defaultValue={query.type} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All types</option>{types.map((type)=><option key={type} value={type}>{type.replaceAll("_"," ")}</option>)}</select><button className="h-10 rounded-lg bg-slate-950 px-5 text-sm font-medium text-white">Search</button><label className="flex items-center gap-2 text-sm text-slate-600 lg:col-span-5"><input type="checkbox" name="openOnly" value="true" defaultChecked={query.openOnly}/> Hide records known to be closed</label></form>
<div className="mt-6 flex items-center justify-between text-sm text-slate-500"><span>{result.total} published opportunities</span><span>Page {result.page} of {result.pages}</span></div>{result.items.length===0?<div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 className="font-semibold text-slate-950">No matching opportunities yet</h2><p className="mt-2 text-sm text-slate-500">No fake vacancies are shown. Try broader filters or return after more source data is published.</p></div>:<div className="mt-6 space-y-4">{result.items.map((item)=><Link key={item.id} href={`/dashboard/opportunities/${item.slug}`} className="block rounded-xl border border-slate-200 bg-white p-5 shadow-sm hover:border-slate-300"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{item.type.replaceAll("_"," ")}</p><h2 className="mt-1 font-semibold text-slate-950">{item.title}</h2><p className="mt-1 text-sm text-slate-500">{item.organization} • {item.country}</p></div><DeadlineBadge state={item.deadlineState as DeadlineState}/></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{item.description || item.researchAreas.join(" • ") || "Description not provided by current source."}</p></Link>)}</div>}
{result.total>0?<div className="mt-8 flex items-center justify-between"><Link aria-disabled={result.page<=1} className={`rounded-lg border px-4 py-2 text-sm font-medium ${result.page<=1?"pointer-events-none border-slate-100 text-slate-300":"border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`} href={pageHref(Math.max(1,result.page-1),query)}>Previous</Link><Link aria-disabled={result.page>=result.pages} className={`rounded-lg border px-4 py-2 text-sm font-medium ${result.page>=result.pages?"pointer-events-none border-slate-100 text-slate-300":"border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`} href={pageHref(Math.min(result.pages,result.page+1),query)}>Next</Link></div>:null}</div>; }
