import Link from "next/link";
import { EmailAccountActions } from "@/components/email/EmailAccountActions";
import { listEmailAccounts, listEmailMessages } from "@/server/email/email-account.service";
import { getCurrentUser } from "@/server/auth/session";

export default async function EmailAccountsPage() {
  const user = await getCurrentUser();
  if (!user) return null;
  const [accounts, messages] = await Promise.all([listEmailAccounts(user.id), listEmailMessages(user.id, 20)]);
  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-slate-500">Communication</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950">Email accounts</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">Connect Gmail or Microsoft with OAuth. ResearVia encrypts provider tokens before storing them.</p></div><div className="flex gap-2"><Link href="/api/v1/email-accounts/google/connect" className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Connect Gmail</Link><Link href="/api/v1/email-accounts/microsoft/connect" className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-800">Connect Microsoft</Link></div></div>
    <div className="grid gap-4 lg:grid-cols-2">{accounts.length ? accounts.map((account) => <section key={account._id.toString()} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">{account.email}</h2><p className="mt-1 text-sm text-slate-500">{account.provider === "GOOGLE" ? "Gmail" : "Microsoft Outlook"} · {account.status.replaceAll("_", " ").toLowerCase()}</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Connected</span></div><p className="mt-4 text-xs text-slate-500">Last synced: {account.lastSyncedAt ? new Date(account.lastSyncedAt).toLocaleString() : "Not yet synced"}</p><div className="mt-4"><EmailAccountActions accountId={account._id.toString()} /></div></section>) : <div className="rounded-xl border border-dashed border-slate-300 bg-white p-8 text-sm text-slate-600 lg:col-span-2">No mailbox is connected. Connect Gmail or Microsoft to send professor outreach and synchronize reply metadata.</div>}</div>
    <section className="rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-950">Recent synced messages</h2><p className="mt-1 text-sm text-slate-500">Only message metadata/snippets used for outreach tracking are shown here.</p></div><div className="divide-y divide-slate-100">{messages.length ? messages.map((message) => <div key={message._id.toString()} className="px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium text-slate-900">{message.subject || "(no subject)"}</p><span className="text-xs font-medium text-slate-500">{message.direction}</span></div><p className="mt-1 text-sm text-slate-600">{message.from}</p><p className="mt-2 line-clamp-2 text-sm text-slate-500">{message.snippet}</p></div>) : <div className="px-5 py-8 text-sm text-slate-500">No synchronized email metadata yet.</div>}</div></section>
  </div>;
}
