import { connectDatabase } from "@/server/db/mongoose";
import { Paper } from "@/server/models/Paper";

type OpenAlexWork={id:string;doi?:string|null;title?:string|null;publication_date?:string|null;cited_by_count?:number;primary_location?:{landing_page_url?:string|null;source?:{display_name?:string|null}|null}|null;authorships?:Array<{author?:{display_name?:string|null}|null}>;topics?:Array<{display_name?:string|null}>;abstract_inverted_index?:Record<string,number[]>|null};
type CrossrefItem={DOI?:string;title?:string[];author?:Array<{given?:string;family?:string}>;URL?:string;"container-title"?:string[];subject?:string[];"is-referenced-by-count"?:number;published?:{"date-parts"?:number[][]};"published-online"?:{"date-parts"?:number[][]};"published-print"?:{"date-parts"?:number[][]}};
function normalizeDoi(value?:string|null){return value?.replace(/^https?:\/\/(dx\.)?doi\.org\//i,"").trim().toLowerCase()||undefined;}
function abstractFromIndex(index?:Record<string,number[]>|null){if(!index)return"";return Object.entries(index).flatMap(([word,positions])=>positions.map((position)=>[position,word] as const)).sort((a,b)=>a[0]-b[0]).map(([,word])=>word).join(" ").slice(0,12000);}
function dateParts(value?:{"date-parts"?:number[][]}){const part=value?.["date-parts"]?.[0];if(!part?.[0])return null;return new Date(Date.UTC(part[0],Math.max(0,(part[1]??1)-1),part[2]??1));}
async function upsertPaper(input:{provider:"OPENALEX"|"CROSSREF";externalId:string;doi?:string;values:Record<string,unknown>}){const filter=input.doi?{doi:input.doi}:{source:input.provider,externalId:input.externalId};return Paper.findOneAndUpdate(filter,{$set:input.values,$setOnInsert:{source:input.provider,externalId:input.externalId,...(input.doi?{doi:input.doi}:{})}},{upsert:true,new:true,runValidators:true});}
export async function syncOpenAlexPapers(query:string,limit:number){await connectDatabase();const url=new URL("https://api.openalex.org/works");url.searchParams.set("search",query);url.searchParams.set("per-page",String(limit));const response=await fetch(url,{headers:{"user-agent":"ResearVia/0.1 academic research discovery"},signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(`OpenAlex request failed: ${response.status}`);const data=await response.json() as {results?:OpenAlexWork[]};let imported=0;for(const work of data.results??[]){if(!work.id||!work.title)continue;const normalizedDoi=normalizeDoi(work.doi);await upsertPaper({provider:"OPENALEX",externalId:work.id,doi:normalizedDoi,values:{title:work.title,authors:(work.authorships??[]).map((a)=>a.author?.display_name).filter((v):v is string=>Boolean(v)),topics:(work.topics??[]).map((t)=>t.display_name).filter((v):v is string=>Boolean(v)),abstract:abstractFromIndex(work.abstract_inverted_index),publicationDate:work.publication_date?new Date(work.publication_date):null,citationCount:work.cited_by_count??0,venue:work.primary_location?.source?.display_name??"",landingUrl:work.primary_location?.landing_page_url??work.id,sourceUrl:work.id,retrievedAt:new Date(),lastVerifiedAt:new Date(),status:"PUBLISHED"}});imported+=1;}return{provider:"OPENALEX" as const,imported};}
export async function syncCrossrefPapers(query:string,limit:number){await connectDatabase();const url=new URL("https://api.crossref.org/works");url.searchParams.set("query",query);url.searchParams.set("rows",String(limit));const response=await fetch(url,{headers:{"user-agent":"ResearVia/0.1 academic research discovery"},signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(`Crossref request failed: ${response.status}`);const data=await response.json() as {message?:{items?:CrossrefItem[]}};let imported=0;for(const work of data.message?.items??[]){const normalizedDoi=normalizeDoi(work.DOI);const title=work.title?.[0]?.trim();const externalId=normalizedDoi??work.URL;if(!title||!externalId)continue;const published=dateParts(work.published??work["published-online"]??work["published-print"]);await upsertPaper({provider:"CROSSREF",externalId,doi:normalizedDoi,values:{title,authors:(work.author??[]).map((a)=>[a.given,a.family].filter(Boolean).join(" ")).filter(Boolean),topics:work.subject??[],publicationDate:published,citationCount:work["is-referenced-by-count"]??0,venue:work["container-title"]?.[0]??"",landingUrl:work.URL??(normalizedDoi?`https://doi.org/${normalizedDoi}`:""),sourceUrl:work.URL??`https://api.crossref.org/works/${encodeURIComponent(externalId)}`,retrievedAt:new Date(),lastVerifiedAt:new Date(),status:"PUBLISHED"}});imported+=1;}return{provider:"CROSSREF" as const,imported};}
