import { JobActions } from "@/components/admin/JobActions";
import { requireAdmin } from "@/server/admin/admin.service";
import { listJobs } from "@/server/jobs/job.service";

export default async function AdminJobsPage() {
  await requireAdmin();
  const jobs = await listJobs(200);
  return <div className="mx-auto max-w-7xl space-y-6"><div><p className="text-sm font-medium text-slate-500">Operations</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Background jobs</h1><p className="mt-2 text-sm text-slate-600">Inspect durable MongoDB-backed work. Failed jobs can be retried; pending/retrying jobs can be cancelled safely.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full divide-y divide-slate-200 text-sm"><thead className="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Job</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Attempts</th><th className="px-5 py-3">Available</th><th className="px-5 py-3">Error</th><th className="px-5 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{jobs.map((job) => <tr key={job._id.toString()} className="align-top"><td className="px-5 py-4"><p className="font-medium text-slate-950">{job.type}</p><p className="mt-1 max-w-xs truncate text-xs text-slate-500">{job.idempotencyKey || job._id.toString()}</p></td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-medium text-slate-700">{job.status}</span></td><td className="px-5 py-4 text-slate-600">{job.attempts}/{job.maxAttempts}</td><td className="px-5 py-4 text-slate-600">{new Date(job.availableAt).toLocaleString()}</td><td className="max-w-md px-5 py-4 text-xs leading-5 text-slate-500">{job.lastError || "—"}</td><td className="px-5 py-4"><JobActions id={job._id.toString()} status={job.status}/></td></tr>)}</tbody></table></div>{jobs.length === 0 ? <p className="p-8 text-center text-sm text-slate-500">No background jobs yet.</p> : null}</div></div>;
}
