import type { LabSearchInput, ProfessorSearchInput, ProgramSearchInput, UniversitySearchInput } from "@/schemas/discovery";
import { prepareDiscoveryDatabase } from "@/server/db/discovery-indexes";
import { AppError } from "@/server/errors/AppError";
import { AcademicProgram } from "@/server/models/AcademicProgram";
import { Professor } from "@/server/models/Professor";
import { ResearchLab } from "@/server/models/ResearchLab";
import { University } from "@/server/models/University";

export type UniversityCard={id:string;name:string;slug:string;country:string;city:string;region:string;website:string;description:string;logoUrl:string;source:string;sourceUrl:string;lastVerifiedAt:string|null};
export type ProfessorCard={id:string;fullName:string;slug:string;universityId:string;universityName:string;universitySlug:string;title:string;department:string;country:string;city:string;email:string;website:string;orcid:string;googleScholar:string;researchAreas:string[];bio:string;publicationCount:number;citedByCount:number;source:string;sourceUrl:string;lastVerifiedAt:string|null;contactEnrichmentStatus:string;contactConfidence:string;contactEmailSource:string;contactWebsiteSource:string;contactEnrichedAt:string|null};
export type LabCard={id:string;name:string;slug:string;universityId:string;universityName:string;universitySlug:string;departmentId:string;departmentName:string;website:string;contactEmail:string;location:string;description:string;researchAreas:string[];professors:{id:string;fullName:string;slug:string;email:string}[];openPositions:string[];fundingSignals:string[];source:string;sourceUrl:string;lastVerifiedAt:string|null};
export type ProgramCard={id:string;name:string;slug:string;universityId:string;universityName:string;universitySlug:string;departmentId:string;departmentName:string;degreeLevel:string;website:string;deadline:string|null;intake:string;funding:string;requirements:string[];researchAreas:string[];description:string;source:string;sourceUrl:string;lastVerifiedAt:string|null};

const populated=(value:unknown)=>value&&typeof value==="object"?value as Record<string,unknown>:{};
const date=(value:unknown)=>value?new Date(value as Date).toISOString():null;
const strings=(value:unknown)=>Array.isArray(value)?value.map(String):[];
const unique=(values:string[])=>[...new Set(values.filter(Boolean))];

function universityDto(value:Record<string,unknown>):UniversityCard{return{id:String(value._id),name:String(value.name),slug:String(value.slug),country:String(value.country),city:String(value.city??""),region:String(value.region??""),website:String(value.website??""),description:String(value.description??""),logoUrl:String(value.logoUrl??""),source:String(value.source??"MANUAL"),sourceUrl:String(value.sourceUrl??""),lastVerifiedAt:date(value.lastVerifiedAt)};}
function professorDto(value:Record<string,unknown>):ProfessorCard{const university=populated(value.universityId);return{id:String(value._id),fullName:String(value.fullName),slug:String(value.slug),universityId:String(university._id??value.universityId??""),universityName:String(university.name??""),universitySlug:String(university.slug??""),title:String(value.title??""),department:String(value.department??""),country:String(value.country),city:String(value.city??""),email:String(value.email??""),website:String(value.website??""),orcid:String(value.orcid??""),googleScholar:String(value.googleScholar??""),researchAreas:strings(value.researchAreas),bio:String(value.bio??""),publicationCount:Number(value.publicationCount??0),citedByCount:Number(value.citedByCount??0),source:String(value.source??"MANUAL"),sourceUrl:String(value.sourceUrl??""),lastVerifiedAt:date(value.lastVerifiedAt),contactEnrichmentStatus:String(value.contactEnrichmentStatus??"NOT_STARTED"),contactConfidence:String(value.contactConfidence??"NONE"),contactEmailSource:String(value.contactEmailSource??"NONE"),contactWebsiteSource:String(value.contactWebsiteSource??"NONE"),contactEnrichedAt:date(value.contactEnrichedAt)};}
function professorSummary(value:unknown){const p=populated(value);return{id:String(p._id??""),fullName:String(p.fullName??""),slug:String(p.slug??""),email:String(p.email??"")};}
function labDto(value:Record<string,unknown>):LabCard{
  const university=populated(value.universityId);
  const department=populated(value.departmentId);
  const candidates=[...(Array.isArray(value.professorIds)?value.professorIds:[]),...(value.principalInvestigatorId?[value.principalInvestigatorId]:[])].filter((item)=>item&&typeof item==="object").map(professorSummary);
  const seen=new Set<string>();
  const professors=candidates.filter((professor)=>{
    if(!professor.id||seen.has(professor.id)) return false;
    seen.add(professor.id);
    return true;
  });
  return{id:String(value._id),name:String(value.name),slug:String(value.slug),universityId:String(university._id??value.universityId??""),universityName:String(university.name??""),universitySlug:String(university.slug??""),departmentId:String(department._id??value.departmentId??""),departmentName:String(department.name??""),website:String(value.website??value.websiteUrl??""),contactEmail:String(value.contactEmail??""),location:String(value.location??""),description:String(value.description??""),researchAreas:unique([...strings(value.researchAreas),...strings(value.researchTopics)]),professors,openPositions:strings(value.openPositions),fundingSignals:strings(value.fundingSignals),source:String(value.source??"MANUAL"),sourceUrl:String(value.sourceUrl??""),lastVerifiedAt:date(value.lastVerifiedAt)};
}
function programDto(value:Record<string,unknown>):ProgramCard{const university=populated(value.universityId);const department=populated(value.departmentId);return{id:String(value._id),name:String(value.name),slug:String(value.slug),universityId:String(university._id??value.universityId??""),universityName:String(university.name??""),universitySlug:String(university.slug??""),departmentId:String(department._id??value.departmentId??""),departmentName:String(department.name??""),degreeLevel:String(value.degreeLevel),website:String(value.website??""),deadline:date(value.deadline),intake:String(value.intake??""),funding:String(value.funding??""),requirements:strings(value.requirements),researchAreas:strings(value.researchAreas),description:String(value.description??""),source:String(value.source??"MANUAL"),sourceUrl:String(value.sourceUrl??""),lastVerifiedAt:date(value.lastVerifiedAt)};}

export async function searchUniversities(input:UniversitySearchInput){await prepareDiscoveryDatabase();const filter={status:"PUBLISHED" as const,...(input.q?{$text:{$search:input.q}}:{}),...(input.country?{country:input.country}:{})};const skip=(input.page-1)*input.limit;const[items,total]=await Promise.all([University.find(filter).sort({name:1}).skip(skip).limit(input.limit).lean(),University.countDocuments(filter)]);return{items:items.map((item)=>universityDto(item as unknown as Record<string,unknown>)),page:input.page,limit:input.limit,total,pages:Math.max(1,Math.ceil(total/input.limit))};}
export async function getUniversityBySlug(slug:string):Promise<UniversityCard>{await prepareDiscoveryDatabase();const item=await University.findOne({slug,status:"PUBLISHED"}).lean();if(!item)throw new AppError("UNIVERSITY_NOT_FOUND",404,"University not found.");return universityDto(item as unknown as Record<string,unknown>);}
export async function searchProfessors(input:ProfessorSearchInput){await prepareDiscoveryDatabase();const filter={status:"PUBLISHED" as const,...(input.q?{$text:{$search:input.q}}:{}),...(input.country?{country:input.country}:{}),...(input.universityId?{universityId:input.universityId}:{}),...(input.researchArea?{researchAreas:input.researchArea}:{})};const skip=(input.page-1)*input.limit;const[items,total]=await Promise.all([Professor.find(filter).sort({fullName:1}).skip(skip).limit(input.limit).populate("universityId","name slug").lean(),Professor.countDocuments(filter)]);return{items:items.map((item)=>professorDto(item as unknown as Record<string,unknown>)),page:input.page,limit:input.limit,total,pages:Math.max(1,Math.ceil(total/input.limit))};}
export async function getProfessorBySlug(slug:string):Promise<ProfessorCard>{await prepareDiscoveryDatabase();const item=await Professor.findOne({slug,status:"PUBLISHED"}).populate("universityId","name slug").lean();if(!item)throw new AppError("PROFESSOR_NOT_FOUND",404,"Professor not found.");return professorDto(item as unknown as Record<string,unknown>);}
export async function searchLabs(input:LabSearchInput){await prepareDiscoveryDatabase();const area=input.researchArea?new RegExp(input.researchArea.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"):null;const filter={status:"PUBLISHED" as const,...(input.q?{$text:{$search:input.q}}:{}),...(input.universityId?{universityId:input.universityId}:{}),...(input.departmentId?{departmentId:input.departmentId}:{}),...(area?{$or:[{researchAreas:area},{researchTopics:area}]}:{})};const skip=(input.page-1)*input.limit;const[items,total]=await Promise.all([ResearchLab.find(filter).sort({name:1}).skip(skip).limit(input.limit).populate("universityId","name slug").populate("departmentId","name").lean(),ResearchLab.countDocuments(filter)]);return{items:items.map((item)=>labDto(item as unknown as Record<string,unknown>)),page:input.page,limit:input.limit,total,pages:Math.max(1,Math.ceil(total/input.limit))};}
export async function getLabBySlug(slug:string):Promise<LabCard>{await prepareDiscoveryDatabase();const item=await ResearchLab.findOne({slug,status:"PUBLISHED"}).populate("universityId","name slug").populate("departmentId","name").populate("professorIds","fullName slug email").populate("principalInvestigatorId","fullName slug email").lean();if(!item)throw new AppError("LAB_NOT_FOUND",404,"Research lab not found.");return labDto(item as unknown as Record<string,unknown>);}
export async function searchPrograms(input:ProgramSearchInput){await prepareDiscoveryDatabase();const filter={status:"PUBLISHED" as const,...(input.q?{$text:{$search:input.q}}:{}),...(input.degreeLevel?{degreeLevel:input.degreeLevel}:{}),...(input.universityId?{universityId:input.universityId}:{}),...(input.departmentId?{departmentId:input.departmentId}:{}),...(input.researchArea?{researchAreas:input.researchArea}:{})};const skip=(input.page-1)*input.limit;const[items,total]=await Promise.all([AcademicProgram.find(filter).sort({name:1}).skip(skip).limit(input.limit).populate("universityId","name slug").populate("departmentId","name").lean(),AcademicProgram.countDocuments(filter)]);return{items:items.map((item)=>programDto(item as unknown as Record<string,unknown>)),page:input.page,limit:input.limit,total,pages:Math.max(1,Math.ceil(total/input.limit))};}
export async function getProgramBySlug(slug:string):Promise<ProgramCard>{await prepareDiscoveryDatabase();const item=await AcademicProgram.findOne({slug,status:"PUBLISHED"}).populate("universityId","name slug").populate("departmentId","name").lean();if(!item)throw new AppError("PROGRAM_NOT_FOUND",404,"Academic program not found.");return programDto(item as unknown as Record<string,unknown>);}
