import { redirect } from "next/navigation";
import { SavedItemEditor } from "@/components/saved/SavedItemEditor";
import { savedItemQuerySchema } from "@/schemas/saved";
import { getCurrentUser } from "@/server/auth/session";
import { listSavedItems } from "@/server/saved/saved.service";

export const metadata = { title: "Saved items | ResearVia" };

export default async function SavedPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await getCurrentUser(); if (!user) redirect("/login");
  const raw = await searchParams;
  const parsed = savedItemQuerySchema.safeParse({ itemType: typeof raw.itemType === "string" ? raw.itemType : "", collection: typeof raw.collection === "string" ? raw.collection : "" });
  const query = parsed.success ? parsed.data : { itemType: "" as const, collection: "" };
  const result = await listSavedItems(user.id, query);
  const comparable = result.items.filter((item) => item.itemType === "SCHOLARSHIP" || item.itemType === "OPPORTUNITY");

  return <div className="mx-auto max-w-6xl"><div className="border-b border-slate-200 pb-6"><p className="text-sm font-medium text-slate-500">Shortlist</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Saved items</h1><p className="mt-2 text-sm text-slate-600">Organize professors, universities, scholarships and opportunities into your own collections with private notes.</p></div><form className="mt-6 flex flex-wrap gap-3 rounded-xl border border-slate-200 bg-white p-4"><select name="itemType" defaultValue={query.itemType} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All item types</option><option value="PROFESSOR">Professors</option><option value="UNIVERSITY">Universities</option><option value="SCHOLARSHIP">Scholarships</option><option value="OPPORTUNITY">Opportunities</option></select><select name="collection" defaultValue={query.collection} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All collections</option>{result.collections.map((collection) => <option key={collection}>{collection}</option>)}</select><button className="h-10 rounded-lg bg-slate-950 px-4 text-sm font-medium text-white">Filter</button></form>{comparable.length >= 2 ? <section className="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-5"><div><h2 className="font-semibold text-slate-950">Compare shortlist</h2><p className="mt-1 text-sm text-slate-500">Choose 2–4 items of the same type.</p></div><form action="/dashboard/compare" className="mt-4 grid gap-2 sm:grid-cols-2">{comparable.map((item) => <label key={item.id} className="flex items-start gap-3 rounded-lg border border-slate-200 bg-white p-3 text-sm"><input type="checkbox" name="saved" value={item.id} className="mt-1 size-4"/><span><span className="block font-medium text-slate-900">{item.title}</span><span className="mt-0.5 block text-xs text-slate-500">{item.itemType} • {item.subtitle}</span></span></label>)}<div className="sm:col-span-2 mt-2"><button className="rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-medium text-white">Compare selected</button></div></form></section> : null}{result.items.length === 0 ? <div className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><h2 className="font-semibold text-slate-950">Nothing saved here yet</h2><p className="mt-2 text-sm text-slate-500">Use Save on any published discovery record to build your shortlist.</p></div> : <div className="mt-6 grid gap-4 lg:grid-cols-2">{result.items.map((item) => <SavedItemEditor key={item.id} initial={item}/>)}</div>}</div>;
}
