import { FundingType, ScholarshipDegreeLevel } from '@prisma/client';
import type { NormalizedScholarship } from './scholarship.types';

export const BOOTSTRAP_SCHOLARSHIPS: NormalizedScholarship[] = [
  {
    title: 'DAAD EPOS Scholarship for Development-Related Postgraduate Courses',
    providerName: 'DAAD',
    providerType: 'government_agency',
    countryCode: 'DE',
    countryName: 'Germany',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master, ScholarshipDegreeLevel.phd],
    fundingType: FundingType.scholarship,
    fundingAmount: 934,
    currency: 'EUR',
    isFullyFunded: true,
    applicationUrl: 'https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/',
    officialSourceUrl: 'https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/',
    description: 'Funding for selected postgraduate programmes in Germany for candidates from developing countries.',
    eligibilityCriteria: 'Open to applicants with academic excellence and relevant professional experience.',
    requiredDocuments: ['CV', 'Transcripts', 'Motivation Letter', 'Recommendation Letters'],
    researchAreas: ['Development Studies', 'Public Policy', 'Engineering'],
    deadline: '2026-11-15',
    sourceExternalId: 'bootstrap-daad-epos',
    metadata: { bootstrap: true, provider: 'DAAD' },
  },
  {
    title: 'Erasmus Mundus Joint Masters Scholarship',
    providerName: 'Erasmus+',
    providerType: 'multilateral_program',
    countryCode: 'EU',
    countryName: 'European Union',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master],
    fundingType: FundingType.scholarship,
    fundingAmount: 1400,
    currency: 'EUR',
    isFullyFunded: true,
    applicationUrl: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    officialSourceUrl: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    description: 'Highly integrated international master programmes delivered by consortia of universities.',
    eligibilityCriteria: 'Bachelor degree holders from any country with strong academic background.',
    requiredDocuments: ['CV', 'Degree Certificate', 'Transcripts', 'Passport'],
    researchAreas: ['Computer Science', 'Public Health', 'Data Science'],
    deadline: '2026-12-20',
    sourceExternalId: 'bootstrap-erasmus-joint-masters',
    metadata: { bootstrap: true, provider: 'Erasmus+' },
  },
  {
    title: 'Fulbright Foreign Student Program',
    providerName: 'Fulbright',
    providerType: 'government_agency',
    countryCode: 'US',
    countryName: 'United States',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master, ScholarshipDegreeLevel.phd],
    fundingType: FundingType.fellowship,
    fundingAmount: 25000,
    currency: 'USD',
    isFullyFunded: true,
    applicationUrl: 'https://foreign.fulbrightonline.org',
    officialSourceUrl: 'https://foreign.fulbrightonline.org',
    description: 'Graduate study and research funding for international students in the United States.',
    eligibilityCriteria: 'Strong academic and leadership profile, country-specific eligibility applies.',
    requiredDocuments: ['CV', 'Study Objective', 'Personal Statement', 'English Test Scores'],
    researchAreas: ['Humanities', 'STEM', 'Social Sciences'],
    deadline: '2026-10-10',
    sourceExternalId: 'bootstrap-fulbright-foreign-student',
    metadata: { bootstrap: true, provider: 'Fulbright' },
  },
  {
    title: 'Chevening Scholarship',
    providerName: 'Chevening',
    providerType: 'government_agency',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master],
    fundingType: FundingType.scholarship,
    fundingAmount: 18000,
    currency: 'GBP',
    isFullyFunded: true,
    applicationUrl: 'https://www.chevening.org/scholarships/',
    officialSourceUrl: 'https://www.chevening.org/scholarships/',
    description: 'Fully funded one-year master scholarships in the United Kingdom.',
    eligibilityCriteria: 'Leadership potential and professional experience required.',
    requiredDocuments: ['CV', 'References', 'Academic Documents'],
    researchAreas: ['Public Policy', 'International Relations', 'Business'],
    deadline: '2026-11-05',
    sourceExternalId: 'bootstrap-chevening',
    metadata: { bootstrap: true, provider: 'Chevening' },
  },
  {
    title: 'MEXT Research Students Scholarship',
    providerName: 'MEXT',
    providerType: 'government_agency',
    countryCode: 'JP',
    countryName: 'Japan',
    degreeLevel: ScholarshipDegreeLevel.phd,
    degreeLevels: [ScholarshipDegreeLevel.master, ScholarshipDegreeLevel.phd],
    fundingType: FundingType.scholarship,
    fundingAmount: 143000,
    currency: 'JPY',
    isFullyFunded: true,
    applicationUrl: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html',
    officialSourceUrl: 'https://www.studyinjapan.go.jp/en/smap-stopj-applications-research.html',
    description: 'Japanese government scholarship for research students and graduate candidates.',
    eligibilityCriteria: 'Applicants must meet embassy or university recommendation requirements.',
    requiredDocuments: ['Research Plan', 'Transcripts', 'Recommendation Letters'],
    researchAreas: ['Engineering', 'Natural Sciences', 'Humanities'],
    deadline: '2026-09-30',
    sourceExternalId: 'bootstrap-mext-research',
    metadata: { bootstrap: true, provider: 'MEXT' },
  },
  {
    title: 'Commonwealth Master Scholarships',
    providerName: 'Commonwealth Scholarship Commission',
    providerType: 'multilateral_program',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master],
    fundingType: FundingType.scholarship,
    fundingAmount: 1600,
    currency: 'GBP',
    isFullyFunded: true,
    applicationUrl: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/',
    officialSourceUrl: 'https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/',
    description: 'Scholarships for candidates from eligible Commonwealth countries pursuing taught masters programmes.',
    eligibilityCriteria: 'Citizens of eligible Commonwealth countries with academic merit and financial need.',
    requiredDocuments: ['CV', 'References', 'Academic Certificates'],
    researchAreas: ['Education', 'Climate Change', 'Health Systems'],
    deadline: '2026-12-01',
    sourceExternalId: 'bootstrap-commonwealth-masters',
    metadata: { bootstrap: true, provider: 'Commonwealth Scholarship Commission' },
  },
  {
    title: 'ETH Excellence Scholarship and Opportunity Programme',
    providerName: 'ETH Zurich',
    providerType: 'university',
    countryCode: 'CH',
    countryName: 'Switzerland',
    universityName: 'ETH Zurich',
    degreeLevel: ScholarshipDegreeLevel.master,
    degreeLevels: [ScholarshipDegreeLevel.master],
    fundingType: FundingType.scholarship,
    fundingAmount: 12000,
    currency: 'CHF',
    isFullyFunded: false,
    applicationUrl: 'https://ethz.ch/en/studies/financial/scholarships/excellencescholarship.html',
    officialSourceUrl: 'https://ethz.ch/en/studies/financial/scholarships/excellencescholarship.html',
    description: 'Merit-based scholarship for outstanding master applicants at ETH Zurich.',
    eligibilityCriteria: 'Excellent academic results and strong motivation required.',
    requiredDocuments: ['CV', 'Pre-Proposal', 'References'],
    researchAreas: ['Robotics', 'Computer Science', 'Energy'],
    deadline: '2026-11-30',
    sourceExternalId: 'bootstrap-eth-esop',
    metadata: { bootstrap: true, provider: 'ETH Zurich' },
  },
  {
    title: 'Gates Cambridge Scholarship',
    providerName: 'Gates Cambridge',
    providerType: 'university',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    universityName: 'University of Cambridge',
    degreeLevel: ScholarshipDegreeLevel.phd,
    degreeLevels: [ScholarshipDegreeLevel.master, ScholarshipDegreeLevel.phd, ScholarshipDegreeLevel.postdoc],
    fundingType: FundingType.scholarship,
    fundingAmount: 21000,
    currency: 'GBP',
    isFullyFunded: true,
    applicationUrl: 'https://www.gatescambridge.org/apply/',
    officialSourceUrl: 'https://www.gatescambridge.org/apply/',
    description: 'Full-cost scholarships for outstanding applicants to the University of Cambridge.',
    eligibilityCriteria: 'Exceptional intellectual ability, leadership, and commitment to improving lives.',
    requiredDocuments: ['CV', 'Research Proposal', 'References'],
    researchAreas: ['Medicine', 'Physics', 'Public Health'],
    deadline: '2026-12-10',
    sourceExternalId: 'bootstrap-gates-cambridge',
    metadata: { bootstrap: true, provider: 'Gates Cambridge' },
  },
];
