"use client";
import { useEffect, useState, type FormEvent } from "react";

type Portal = { refereeName:string; institution:string; refereeTitle:string; applicationName:string; deadline:string|null; status:string; expiresAt:string|null; submittedAt:string|null };

export function RefereePortalClient({ token }: { token: string }) {
  const [portal,setPortal]=useState<Portal|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");
  useEffect(()=>{let active=true;fetch(`/api/v1/referee/${encodeURIComponent(token)}`,{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body?.error?.message||"Unable to open referee portal.");if(active)setPortal(body.data??body);}).catch(e=>active&&setError(e instanceof Error?e.message:"Unable to open referee portal.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[token]);
  async function action(kind:"CONFIRM"|"DECLINE"){setBusy(true);setError("");try{const form=new FormData();form.set("action",kind);const r=await fetch(`/api/v1/referee/${encodeURIComponent(token)}`,{method:"POST",body:form});const body=await r.json();if(!r.ok)throw new Error(body?.error?.message||"Action failed.");setPortal(body.data??body);}catch(e){setError(e instanceof Error?e.message:"Action failed.");}finally{setBusy(false)}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const form=new FormData(event.currentTarget);form.set("action","SUBMIT");form.set("message",message);const r=await fetch(`/api/v1/referee/${encodeURIComponent(token)}`,{method:"POST",body:form});const body=await r.json();if(!r.ok)throw new Error(body?.error?.message||"Submission failed.");setPortal(body.data??body);event.currentTarget.reset();setMessage("");}catch(e){setError(e instanceof Error?e.message:"Submission failed.");}finally{setBusy(false)}}
  if(loading)return <div className="rounded-xl border border-slate-200 bg-white p-8 text-sm text-slate-500">Opening secure referee portal…</div>;
  if(error&&!portal)return <div className="rounded-xl border border-red-200 bg-red-50 p-8"><h1 className="text-xl font-semibold text-red-950">Unable to open request</h1><p className="mt-2 text-sm text-red-800">{error}</p></div>;
  if(!portal)return null;
  const received=portal.status==="RECEIVED";
  return <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="border-b border-slate-100 pb-6"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">Confidential recommendation portal</p><h1 className="mt-2 text-2xl font-semibold text-slate-950">{portal.applicationName}</h1><p className="mt-2 text-sm text-slate-600">For {portal.refereeName}{portal.institution?` • ${portal.institution}`:""}. Your letter is stored separately from the applicant’s document vault and is not exposed through the student download APIs.</p>{portal.deadline&&<p className="mt-3 text-sm font-medium text-slate-700">Requested deadline: {new Date(portal.deadline).toLocaleDateString()}</p>}</div>{error&&<p className="mt-5 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{received?<div className="mt-6 rounded-xl bg-emerald-50 p-5"><h2 className="font-semibold text-emerald-950">Recommendation submitted</h2><p className="mt-1 text-sm text-emerald-800">Thank you. The applicant has been notified that the confidential recommendation was received.</p></div>:portal.status==="DECLINED"?<div className="mt-6 rounded-xl bg-slate-50 p-5"><h2 className="font-semibold text-slate-900">Request declined</h2><p className="mt-1 text-sm text-slate-600">The applicant can send a new request if circumstances change.</p></div>:<><div className="mt-6 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>action("CONFIRM")} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-800 disabled:opacity-50">Confirm I can recommend</button><button disabled={busy} onClick={()=>action("DECLINE")} className="rounded-lg border border-slate-200 px-4 py-2 text-sm text-slate-600 disabled:opacity-50">Decline request</button></div><form onSubmit={submit} className="mt-7 space-y-4"><div><label className="text-sm font-medium text-slate-800">Confidential letter</label><input required name="file" type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="mt-2 block w-full rounded-lg border border-slate-200 p-2 text-sm"/><p className="mt-1 text-xs text-slate-500">PDF, DOC, or DOCX; maximum 10 MB.</p></div><div><label className="text-sm font-medium text-slate-800">Optional note</label><textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={8000} className="mt-2 min-h-28 w-full rounded-lg border border-slate-200 p-3 text-sm"/></div><button disabled={busy} className="rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?"Submitting…":"Submit confidential recommendation"}</button></form></>}</div>;
}
