import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AppError } from "@/server/errors/AppError";
import { getUniversityBySlug, searchProfessors } from "@/server/discovery/discovery.service";

type Props={params:Promise<{slug:string}>};async function load(slug:string){try{return await getUniversityBySlug(slug);}catch(error){if(error instanceof AppError&&error.status===404)return null;throw error;}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const item=await load(slug);if(!item)return{title:"University not found | ResearVia",robots:{index:false,follow:false}};return{title:`${item.name} | ResearVia`,description:(item.description||`${item.name} in ${item.country}`).slice(0,160),alternates:{canonical:`/universities/${item.slug}`},robots:{index:true,follow:true}};}
export default async function UniversityPage({params}:Props){const {slug}=await params;const item=await load(slug);if(!item)notFound();const professors=await searchProfessors({q:"",country:"",researchArea:"",universityId:item.id,page:1,limit:12});const structured={"@context":"https://schema.org","@type":"CollegeOrUniversity",name:item.name,address:{"@type":"PostalAddress",addressLocality:item.city||undefined,addressRegion:item.region||undefined,addressCountry:item.country},url:item.website||undefined};return <main className="mx-auto min-h-screen max-w-5xl px-6 py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><div className="flex items-center justify-between gap-4"><Link href="/universities" className="text-sm font-medium text-slate-600">← Universities</Link><Link href="/login" className="text-sm font-medium">Sign in</Link></div><article className="mt-8 rounded-2xl border bg-white p-7 shadow-sm"><p className="text-sm font-medium text-slate-500">{[item.city,item.region,item.country].filter(Boolean).join(" · ")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{item.name}</h1><p className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-700">{item.description||"No public description is available from the current source."}</p><div className="mt-6 flex flex-wrap gap-3">{item.website?<a target="_blank" rel="noreferrer" href={item.website} className="rounded-md border px-3 py-2 text-sm font-medium">Official website</a>:null}{item.sourceUrl?<a target="_blank" rel="noreferrer" href={item.sourceUrl} className="rounded-md border px-3 py-2 text-sm font-medium">Verify source</a>:null}</div><p className="mt-5 text-xs text-slate-500">Source: {item.source} · Last verified: {item.lastVerifiedAt?new Date(item.lastVerifiedAt).toLocaleDateString():"Not recorded"}</p></article><section className="mt-8"><h2 className="text-xl font-semibold">Published professors</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{professors.items.map(professor=><Link key={professor.id} href={`/professors/${professor.slug}`} className="rounded-xl border bg-white p-4"><h3 className="font-semibold">{professor.fullName}</h3><p className="mt-1 text-sm text-slate-600">{[professor.title,professor.department].filter(Boolean).join(" · ")}</p></Link>)}{professors.items.length===0?<p className="text-sm text-slate-600">No published professor records are currently linked to this university.</p>:null}</div></section></main>}
