import { SavePaperButton } from "@/components/research/SavePaperButton";
import { searchLabs, searchPapers, topicExplorer } from "@/server/research/research.service";

type Props = { searchParams: Promise<{ q?: string }> };

export default async function ResearchDiscoveryPage({ searchParams }: Props) {
  const params = await searchParams;
  const q = params.q?.trim() ?? "";
  const [papers, labs, topic] = await Promise.all([searchPapers(q, 20), searchLabs(q, 12), q ? topicExplorer(q) : Promise.resolve({ topic: "", relatedTopics: [] as Array<{ topic: string; count: number }>, papers: [], labs: [] })]);
  return <div className="space-y-8">
    <div><p className="text-sm font-medium text-slate-500">Research intelligence</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Papers, labs & topics</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Explore verified scholarly metadata already stored in ResearVia. Paper facts keep provider provenance; lab records are shown only when published.</p></div>
    <form className="flex gap-2" action="/dashboard/research"><label className="sr-only" htmlFor="research-q">Research topic</label><input id="research-q" name="q" defaultValue={q} placeholder="e.g. federated learning, V2X security, computer vision" className="min-w-0 flex-1 rounded-md border bg-white px-3 py-2 text-sm"/><button className="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Explore</button></form>
    {q && topic.relatedTopics.length > 0 ? <section><h2 className="text-lg font-semibold">Related topics</h2><div className="mt-3 flex flex-wrap gap-2">{topic.relatedTopics.map((item) => <a key={item.topic} href={`/dashboard/research?q=${encodeURIComponent(item.topic)}`} className="rounded-full border bg-white px-3 py-1.5 text-xs text-slate-700">{item.topic} · {item.count}</a>)}</div></section> : null}
    <section><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">Papers</h2><p className="text-sm text-slate-500">{papers.length} result{papers.length === 1 ? "" : "s"}</p></div><a href="/dashboard/reading" className="text-sm font-medium underline underline-offset-4">Reading list</a></div><div className="mt-4 grid gap-4 xl:grid-cols-2">{papers.map((paper) => <article key={paper._id.toString()} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{paper.source}{paper.venue ? ` · ${paper.venue}` : ""}</p><h3 className="mt-2 font-semibold leading-snug">{paper.title}</h3></div><SavePaperButton paperId={paper._id.toString()}/></div>{paper.authors.length > 0 ? <p className="mt-3 text-sm text-slate-600">{paper.authors.slice(0, 6).join(", ")}{paper.authors.length > 6 ? " et al." : ""}</p> : null}<div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500">{paper.publicationDate ? <span>{new Date(paper.publicationDate).getUTCFullYear()}</span> : <span>Date unknown</span>}<span>·</span><span>{paper.citationCount} citations</span>{paper.doi ? <><span>·</span><span>DOI {paper.doi}</span></> : null}</div>{paper.topics.length > 0 ? <p className="mt-3 text-xs text-slate-500">{paper.topics.slice(0, 6).join(" · ")}</p> : null}{paper.landingUrl ? <a href={paper.landingUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-medium underline underline-offset-4">Open source record</a> : null}</article>)}{papers.length === 0 ? <p className="text-sm text-slate-600">No published papers match this query yet. An administrator can import metadata from OpenAlex or Crossref.</p> : null}</div></section>
    <section><h2 className="text-lg font-semibold">Research labs</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{labs.map((lab) => <article key={lab._id.toString()} className="rounded-xl border bg-white p-5 shadow-sm"><h3 className="font-semibold">{lab.name}</h3>{lab.description ? <p className="mt-2 line-clamp-3 text-sm text-slate-600">{lab.description}</p> : null}{lab.researchTopics.length > 0 ? <p className="mt-3 text-xs text-slate-500">{lab.researchTopics.slice(0, 8).join(" · ")}</p> : null}{lab.openPositions.length > 0 ? <p className="mt-3 text-sm font-medium text-emerald-700">Published position signals: {lab.openPositions.length}</p> : null}{lab.websiteUrl ? <a href={lab.websiteUrl} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-medium underline underline-offset-4">Lab website</a> : null}</article>)}{labs.length === 0 ? <p className="text-sm text-slate-600">No published lab records match this query yet.</p> : null}</div></section>
  </div>;
}
