import { connectDatabase } from "@/server/db/mongoose";
import { AppError } from "@/server/errors/AppError";
import { Application } from "@/server/models/Application";
import { CalendarEvent } from "@/server/models/CalendarEvent";
import { EmailAccount } from "@/server/models/EmailAccount";
import { Job } from "@/server/models/Job";
import { PrivacyPreference } from "@/server/models/PrivacyPreference";
import { PublicStudentProfile } from "@/server/models/PublicStudentProfile";
import { ReadingItem } from "@/server/models/ReadingItem";
import { ResearchProject } from "@/server/models/ResearchProject";
import { SavedItem } from "@/server/models/SavedItem";
import { StudentDocument } from "@/server/models/StudentDocument";
import { StudentProfile } from "@/server/models/StudentProfile";
import { StudentPublication } from "@/server/models/StudentPublication";
import { User } from "@/server/models/User";
import { UserSession } from "@/server/models/UserSession";
import { Watchlist } from "@/server/models/Watchlist";
import { WritingWorkspace } from "@/server/models/WritingWorkspace";
import { verifyPassword } from "@/server/security/password";

export async function getPrivacyPreferences(userId:string){await connectDatabase();return PrivacyPreference.findOneAndUpdate({userId},{$setOnInsert:{userId}},{upsert:true,new:true,setDefaultsOnInsert:true}).lean();}
export async function updatePrivacyPreferences(userId:string,input:{aiProcessingAllowed?:boolean;recommendationPersonalization?:boolean;analyticsAllowed?:boolean;emailSyncAllowed?:boolean}){await connectDatabase();return PrivacyPreference.findOneAndUpdate({userId},{$set:input,$setOnInsert:{userId}},{upsert:true,new:true,runValidators:true}).lean();}
export async function listUserSessions(userId:string,currentTokenHash?:string){await connectDatabase();const sessions=await UserSession.find({userId,revokedAt:null,expiresAt:{$gt:new Date()}}).select("+tokenHash").sort({lastSeenAt:-1}).lean();return sessions.map((item)=>({id:item._id.toString(),createdAt:item.createdAt,lastSeenAt:item.lastSeenAt,expiresAt:item.expiresAt,ipAddress:item.ipAddress,userAgent:item.userAgent,isCurrent:Boolean(currentTokenHash&&item.tokenHash===currentTokenHash)}));}
export async function revokeUserSession(userId:string,sessionId:string){await connectDatabase();const result=await UserSession.updateOne({_id:sessionId,userId,revokedAt:null},{$set:{revokedAt:new Date()}});if(!result.matchedCount)throw new AppError("SESSION_NOT_FOUND",404,"Active session not found.");}
export async function revokeOtherSessions(userId:string,currentTokenHash:string){await connectDatabase();await UserSession.updateMany({userId,tokenHash:{$ne:currentTokenHash},revokedAt:null},{$set:{revokedAt:new Date()}});}
export async function exportStudentData(userId:string){await connectDatabase();const [user,profile,publicProfile,preferences,publications,documents,saved,applications,projects,reading,watchlists,calendar,writing,emailAccounts,sessions]=await Promise.all([User.findById(userId).lean(),StudentProfile.findOne({userId}).lean(),PublicStudentProfile.findOne({userId}).lean(),PrivacyPreference.findOne({userId}).lean(),StudentPublication.find({userId}).lean(),StudentDocument.find({userId}).lean(),SavedItem.find({userId}).lean(),Application.find({userId}).lean(),ResearchProject.find({userId}).lean(),ReadingItem.find({userId}).lean(),Watchlist.find({userId}).lean(),CalendarEvent.find({userId}).lean(),WritingWorkspace.find({userId}).lean(),EmailAccount.find({userId}).select("provider email status connectedAt lastSyncedAt disconnectedAt").lean(),UserSession.find({userId}).select("createdAt expiresAt lastSeenAt revokedAt ipAddress userAgent").lean()]);return{exportedAt:new Date().toISOString(),user:user?{id:user._id.toString(),email:user.email,displayName:user.displayName,role:user.role,emailVerifiedAt:user.emailVerifiedAt,createdAt:user.createdAt}:null,profile,publicProfile,preferences,publications,documents:documents.map((item)=>({id:item._id.toString(),kind:item.kind,originalName:item.originalName,mimeType:item.mimeType,size:item.size,createdAt:item.createdAt})),saved,applications,projects,reading,watchlists,calendar,writing,emailAccounts,sessions};}
export async function requestAccountDeletion(userId:string,password:string){const connection=await connectDatabase();const user=await User.findById(userId).select("+passwordHash");if(!user?.passwordHash||!(await verifyPassword(password,user.passwordHash)))throw new AppError("INVALID_PASSWORD",401,"Current password is incorrect.");const documents=await StudentDocument.find({userId}).select("fileId").lean();const fileIds=documents.map((item)=>item.fileId.toString());const session=await connection.startSession();try{await session.withTransaction(async()=>{const anonymous=`deleted-${user._id.toString()}@deleted.invalid`;await User.updateOne({_id:userId},{$set:{email:anonymous,displayName:"Deleted user",status:"DELETED",passwordHash:null,emailVerifiedAt:null}},{session});await Promise.all([UserSession.deleteMany({userId},{session}),PrivacyPreference.deleteMany({userId},{session}),PublicStudentProfile.deleteMany({userId},{session}),StudentProfile.deleteMany({userId},{session}),StudentPublication.deleteMany({userId},{session}),StudentDocument.deleteMany({userId},{session}),SavedItem.deleteMany({userId},{session}),Application.deleteMany({userId},{session}),ResearchProject.deleteMany({userId},{session}),ReadingItem.deleteMany({userId},{session}),Watchlist.deleteMany({userId},{session}),CalendarEvent.deleteMany({userId},{session}),WritingWorkspace.deleteMany({userId},{session}),EmailAccount.deleteMany({userId},{session})]);if(fileIds.length)await Job.create([{type:"DELETE_GRIDFS_FILES",payload:{fileIds},status:"PENDING",attempts:0,maxAttempts:8,availableAt:new Date(),lockedAt:null,lockedBy:null,lastError:null,completedAt:null,idempotencyKey:`delete-gridfs:${userId}`}],{session});});}finally{await session.endSession();}return{deleted:true,storageCleanupQueued:fileIds.length>0};}
