import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { AppError } from "@/server/errors/AppError";
import { getProfessorBySlug } from "@/server/discovery/discovery.service";

type Props={params:Promise<{slug:string}>};
async function load(slug:string){try{return await getProfessorBySlug(slug);}catch(error){if(error instanceof AppError&&error.status===404)return null;throw error;}}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const item=await load(slug);if(!item)return{title:"Professor not found | ResearVia",robots:{index:false,follow:false}};return{title:`${item.fullName} | Professor profile | ResearVia`,description:(item.bio||`${item.fullName} — ${item.department||"academic researcher"} in ${item.country}`).slice(0,160),alternates:{canonical:`/professors/${item.slug}`},robots:{index:true,follow:true},openGraph:{title:item.fullName,description:(item.bio||item.researchAreas.join(", ")).slice(0,180),type:"profile"}};}
export default async function ProfessorPage({params}:Props){const {slug}=await params;const item=await load(slug);if(!item)notFound();const structured={"@context":"https://schema.org","@type":"Person",name:item.fullName,jobTitle:item.title||undefined,affiliation:item.universityName?{"@type":"CollegeOrUniversity",name:item.universityName}:undefined,url:item.website||undefined,sameAs:[item.orcid?`https://orcid.org/${item.orcid}`:"",item.googleScholar,item.website].filter(Boolean),knowsAbout:item.researchAreas};return <main className="mx-auto min-h-screen max-w-4xl px-6 py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><div className="flex items-center justify-between gap-4"><Link href="/professors" className="text-sm font-medium text-slate-600">← Professors</Link><Link href="/login" className="text-sm font-medium">Sign in to save or contact</Link></div><article className="mt-8 rounded-2xl border bg-white p-7 shadow-sm"><p className="text-sm font-medium text-slate-500">{[item.title,item.department,item.universityName,item.country].filter(Boolean).join(" · ")}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{item.fullName}</h1>{item.bio?<p className="mt-5 whitespace-pre-line text-sm leading-7 text-slate-700">{item.bio}</p>:null}{item.researchAreas.length?<section className="mt-7"><h2 className="font-semibold">Research areas</h2><div className="mt-3 flex flex-wrap gap-2">{item.researchAreas.map(area=><span key={area} className="rounded-full bg-slate-100 px-3 py-1 text-sm">{area}</span>)}</div></section>:null}<dl className="mt-7 grid gap-4 border-y py-5 sm:grid-cols-3"><div><dt className="text-xs uppercase tracking-wide text-slate-400">Publications</dt><dd className="mt-1 font-semibold">{item.publicationCount}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Citations</dt><dd className="mt-1 font-semibold">{item.citedByCount}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Last verified</dt><dd className="mt-1 text-sm">{item.lastVerifiedAt?new Date(item.lastVerifiedAt).toLocaleDateString():"Not recorded"}</dd></div></dl><div className="mt-6 flex flex-wrap gap-3">{item.website?<a target="_blank" rel="noreferrer" href={item.website} className="rounded-md border px-3 py-2 text-sm font-medium">Official website</a>:null}{item.sourceUrl?<a target="_blank" rel="noreferrer" href={item.sourceUrl} className="rounded-md border px-3 py-2 text-sm font-medium">Verify source</a>:null}{item.universitySlug?<Link href={`/universities/${item.universitySlug}`} className="rounded-md border px-3 py-2 text-sm font-medium">University</Link>:null}</div></article><p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Contact information and research activity can change. Verify details on the official source before outreach.</p></main>}
