import { prepareDiscoveryDatabase } from "@/server/db/discovery-indexes";
import { prepareOpportunityDatabase } from "@/server/db/opportunity-indexes";
import { prepareSavedDatabase } from "@/server/db/saved-indexes";
import { AppError } from "@/server/errors/AppError";
import { AcademicProgram } from "@/server/models/AcademicProgram";
import { Opportunity } from "@/server/models/Opportunity";
import { ResearchLab } from "@/server/models/ResearchLab";
import { SavedItem } from "@/server/models/SavedItem";
import { Scholarship } from "@/server/models/Scholarship";

export type ComparisonItem={savedId:string;targetId:string;title:string;href:string;fields:Record<string,string>};
export type ComparisonResult={type:"SCHOLARSHIP"|"OPPORTUNITY"|"LAB"|"PROGRAM";labels:string[];items:ComparisonItem[]};
const formatDate=(value:unknown)=>value?new Intl.DateTimeFormat("en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(value as Date)):"Unknown";
const list=(value:unknown)=>Array.isArray(value)&&value.length?value.map(String).join(", "):"Not provided";
const populatedName=(value:unknown)=>value&&typeof value==="object"?String((value as {name?:unknown}).name??"Not provided"):"Not provided";

export async function compareSavedItems(userId:string,requestedIds:string[]):Promise<ComparisonResult>{
 await Promise.all([prepareSavedDatabase(),prepareOpportunityDatabase(),prepareDiscoveryDatabase()]);
 const ids=[...new Set(requestedIds)].slice(0,5);if(ids.length<2||ids.length>4||ids.some((id)=>!/^[a-f\d]{24}$/i.test(id)))throw new AppError("INVALID_COMPARISON",400,"Choose between two and four comparable saved items.");
 const saved=await SavedItem.find({_id:{$in:ids},userId,itemType:{$in:["SCHOLARSHIP","OPPORTUNITY","LAB","PROGRAM"]}}).lean();if(saved.length!==ids.length)throw new AppError("INVALID_COMPARISON",400,"One or more selected items cannot be compared.");
 const byId=new Map(saved.map((item)=>[String(item._id),item]));const ordered=ids.map((id)=>byId.get(id)).filter((item):item is NonNullable<typeof item>=>Boolean(item));const type=String(ordered[0]?.itemType) as ComparisonResult["type"];if(ordered.some((item)=>item.itemType!==type))throw new AppError("MIXED_COMPARISON",400,"Compare items of the same type.");const targetIds=ordered.map((item)=>item.targetId);
 if(type==="SCHOLARSHIP"){const targets=await Scholarship.find({_id:{$in:targetIds},status:"PUBLISHED"}).populate("universityId","name").lean();const map=new Map(targets.map((item)=>[String(item._id),item]));if(targets.length!==ordered.length)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"One or more scholarship records are no longer published.");const labels=["Provider","Country","University","Funding","Funding amount","Deadline","Degree levels","Study fields","Language requirements","Required documents","Eligibility"];return{type,labels,items:ordered.map((savedItem)=>{const item=map.get(String(savedItem.targetId));if(!item)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"Scholarship record unavailable.");return{savedId:String(savedItem._id),targetId:String(item._id),title:item.name,href:`/dashboard/scholarships/${item.slug}`,fields:{Provider:item.provider,Country:item.country,University:populatedName(item.universityId),Funding:item.fundingType,"Funding amount":item.fundingAmount||"Not provided",Deadline:formatDate(item.deadline),"Degree levels":list(item.degreeLevels),"Study fields":list(item.studyFields),"Language requirements":list(item.languageRequirements),"Required documents":list(item.requiredDocuments),Eligibility:item.eligibility||"Not provided"}};})};}
 if(type==="OPPORTUNITY"){const targets=await Opportunity.find({_id:{$in:targetIds},status:"PUBLISHED"}).populate("universityId","name").lean();const map=new Map(targets.map((item)=>[String(item._id),item]));if(targets.length!==ordered.length)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"One or more opportunity records are no longer published.");const labels=["Organization","Type","Country","University","Funding","Deadline","Fields","Research areas","Required documents","Eligibility"];return{type,labels,items:ordered.map((savedItem)=>{const item=map.get(String(savedItem.targetId));if(!item)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"Opportunity record unavailable.");return{savedId:String(savedItem._id),targetId:String(item._id),title:item.title,href:`/dashboard/opportunities/${item.slug}`,fields:{Organization:item.organization,Type:item.type.replaceAll("_"," "),Country:item.country,University:populatedName(item.universityId),Funding:item.funding||"Not provided",Deadline:formatDate(item.deadline),Fields:list(item.fields),"Research areas":list(item.researchAreas),"Required documents":list(item.requiredDocuments),Eligibility:item.eligibility||"Not provided"}};})};}
 if(type==="LAB"){const targets=await ResearchLab.find({_id:{$in:targetIds},status:"PUBLISHED"}).populate("universityId","name").populate("departmentId","name").lean();const map=new Map(targets.map((item)=>[String(item._id),item]));if(targets.length!==ordered.length)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"One or more lab records are no longer published.");const labels=["University","Department","Research areas","Open positions","Funding signals","Location","Public contact"];return{type,labels,items:ordered.map((savedItem)=>{const item=map.get(String(savedItem.targetId));if(!item)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"Lab record unavailable.");const areas=[...(item.researchAreas??[]),...(item.researchTopics??[])];return{savedId:String(savedItem._id),targetId:String(item._id),title:item.name,href:`/dashboard/labs/${item.slug}`,fields:{University:populatedName(item.universityId),Department:populatedName(item.departmentId),"Research areas":list([...new Set(areas)]),"Open positions":list(item.openPositions),"Funding signals":list(item.fundingSignals),Location:item.location||"Not provided","Public contact":item.contactEmail||"Not provided"}};})};}
 const targets=await AcademicProgram.find({_id:{$in:targetIds},status:"PUBLISHED"}).populate("universityId","name").populate("departmentId","name").lean();const map=new Map(targets.map((item)=>[String(item._id),item]));if(targets.length!==ordered.length)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"One or more program records are no longer published.");const labels=["University","Department","Degree level","Deadline","Intake","Funding","Requirements","Research areas"];return{type,labels,items:ordered.map((savedItem)=>{const item=map.get(String(savedItem.targetId));if(!item)throw new AppError("COMPARISON_SOURCE_UNAVAILABLE",409,"Program record unavailable.");return{savedId:String(savedItem._id),targetId:String(item._id),title:item.name,href:`/dashboard/programs/${item.slug}`,fields:{University:populatedName(item.universityId),Department:populatedName(item.departmentId),"Degree level":item.degreeLevel.replaceAll("_"," "),Deadline:formatDate(item.deadline),Intake:item.intake||"Not provided",Funding:item.funding||"Not provided",Requirements:list(item.requirements),"Research areas":list(item.researchAreas)}};})};
}
