import mongoose from "mongoose";
import { prepareProductivityDatabase } from "@/server/db/productivity-indexes";
import { AppError } from "@/server/errors/AppError";
import { enqueueJob } from "@/server/jobs/job.service";
import { SupportTicket } from "@/server/models/SupportTicket";
import { notifyUser } from "@/server/notifications/notification.service";

export async function listAdminSupportTickets(){await prepareProductivityDatabase();return SupportTicket.find({}).populate("userId","displayName email").sort({status:1,priority:-1,updatedAt:-1}).limit(500).lean();}
export async function updateAdminSupportTicket(id:string,input:{status?:"OPEN"|"IN_PROGRESS"|"WAITING_USER"|"RESOLVED"|"CLOSED";priority?:"LOW"|"NORMAL"|"HIGH"|"URGENT"}){if(!mongoose.isValidObjectId(id))throw new AppError("SUPPORT_TICKET_NOT_FOUND",404,"Support ticket not found.");await prepareProductivityDatabase();const set:Record<string,unknown>={...input};if(input.status==="RESOLVED"||input.status==="CLOSED")set.resolvedAt=new Date();const item=await SupportTicket.findByIdAndUpdate(id,{$set:set},{returnDocument:"after",runValidators:true}).lean();if(!item)throw new AppError("SUPPORT_TICKET_NOT_FOUND",404,"Support ticket not found.");return item;}
export async function replyAdminSupportTicket(id:string,body:string){if(!mongoose.isValidObjectId(id))throw new AppError("SUPPORT_TICKET_NOT_FOUND",404,"Support ticket not found.");await prepareProductivityDatabase();const item=await SupportTicket.findByIdAndUpdate(id,{$push:{messages:{authorRole:"ADMIN",body,createdAt:new Date()}},$set:{status:"WAITING_USER"}},{returnDocument:"after",runValidators:true});if(!item)throw new AppError("SUPPORT_TICKET_NOT_FOUND",404,"Support ticket not found.");const notification=await notifyUser({userId:item.userId.toString(),type:"SUPPORT_REPLY",title:"Support replied",message:`New reply on: ${item.subject}`,href:"/dashboard/support",dedupeKey:`support-reply:${item._id}:${item.messages.length}`,metadata:{ticketId:item._id.toString()}});await enqueueJob({type:"SEND_PUSH_NOTIFICATION",payload:{notificationId:notification._id.toString()},idempotencyKey:`push:${notification._id}`,maxAttempts:4});return item.toObject();}
