import type { Metadata } from "next";
import Link from "next/link";
import { professorSearchSchema } from "@/schemas/discovery";
import { searchProfessors } from "@/server/discovery/discovery.service";

export const metadata: Metadata = { title: "Find professors | ResearVia", description: "Search published professor and researcher profiles by country and research area.", alternates: { canonical: "/professors" }, robots: { index: true, follow: true } };
type Search = Promise<Record<string, string | string[] | undefined>>;
const scalar = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";

export default async function ProfessorsPage({ searchParams }: { searchParams: Search }) {
  const raw = await searchParams;
  const input = professorSearchSchema.parse({ q: scalar(raw.q), country: scalar(raw.country), researchArea: scalar(raw.researchArea), page: scalar(raw.page) || "1", limit: "24" });
  const result = await searchProfessors(input);
  return <main className="mx-auto min-h-screen max-w-6xl px-6 py-12"><header className="flex flex-wrap items-center justify-between gap-4"><Link href="/" className="text-lg font-semibold">ResearVia</Link><div className="flex gap-3 text-sm"><Link href="/universities">Universities</Link><Link href="/scholarships">Scholarships</Link><Link href="/opportunities">Opportunities</Link><Link href="/login" className="font-medium">Sign in</Link></div></header><section className="mt-12"><p className="text-sm font-medium text-slate-500">Public academic discovery</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Find professors and researchers</h1><p className="mt-3 max-w-3xl text-slate-600">Only published records are shown. Always verify current affiliation, research activity and contact details at the cited source.</p><form className="mt-7 grid gap-3 rounded-xl border bg-white p-4 md:grid-cols-4"><input name="q" defaultValue={input.q} placeholder="Name, department or topic" className="rounded-md border px-3 py-2 text-sm"/><input name="country" defaultValue={input.country} placeholder="Country" className="rounded-md border px-3 py-2 text-sm"/><input name="researchArea" defaultValue={input.researchArea} placeholder="Research area" className="rounded-md border px-3 py-2 text-sm"/><button className="rounded-md bg-slate-950 px-4 py-2 text-sm font-medium text-white">Search</button></form></section><section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{result.items.map((item)=><Link key={item.id} href={`/professors/${item.slug}`} className="rounded-xl border bg-white p-5 transition hover:border-slate-400"><p className="text-xs font-medium text-slate-500">{item.country}{item.universityName ? ` · ${item.universityName}` : ""}</p><h2 className="mt-2 text-lg font-semibold">{item.fullName}</h2><p className="mt-1 text-sm text-slate-600">{[item.title,item.department].filter(Boolean).join(" · ") || "Academic researcher"}</p>{item.researchAreas.length?<p className="mt-4 text-sm text-slate-600">{item.researchAreas.slice(0,4).join(" · ")}</p>:null}</Link>)}{result.items.length===0?<div className="col-span-full rounded-xl border border-dashed p-8 text-center text-sm text-slate-600">No published professors matched these filters.</div>:null}</section><nav className="mt-8 flex items-center justify-between text-sm"><span>Page {result.page} of {result.pages} · {result.total} records</span><div className="flex gap-2">{result.page>1?<Link className="rounded-md border px-3 py-2" href={{pathname:"/professors",query:{q:input.q,country:input.country,researchArea:input.researchArea,page:result.page-1}}}>Previous</Link>:null}{result.page<result.pages?<Link className="rounded-md border px-3 py-2" href={{pathname:"/professors",query:{q:input.q,country:input.country,researchArea:input.researchArea,page:result.page+1}}}>Next</Link>:null}</div></nav></main>;
}
