import { createHash } from "node:crypto";
import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { XMLParser } from "fast-xml-parser";
import { connectDatabase } from "@/server/db/mongoose";
import { AppError } from "@/server/errors/AppError";
import { AcademicFeedSource } from "@/server/models/AcademicFeedSource";
import { Opportunity } from "@/server/models/Opportunity";
import { Scholarship } from "@/server/models/Scholarship";

const MAX_FEED_BYTES = 2 * 1024 * 1024;
function privateIp(address:string){return /^(127\.|10\.|192\.168\.|169\.254\.|0\.|::1$|fc|fd|fe80)/i.test(address)||/^172\.(1[6-9]|2\d|3[01])\./.test(address);}
export async function assertSafeFeedUrl(value:string){let url:URL;try{url=new URL(value);}catch{throw new AppError("INVALID_FEED_URL",400,"Feed URL is invalid.");}if(url.protocol!=="https:"||url.username||url.password)throw new AppError("UNSAFE_FEED_URL",400,"Feed URLs must use HTTPS without embedded credentials.");const host=url.hostname.toLowerCase();if(host==="localhost"||host.endsWith(".localhost")||host.endsWith(".local")||host.endsWith(".internal"))throw new AppError("UNSAFE_FEED_URL",400,"Private feed hosts are not allowed.");if(isIP(host)){if(privateIp(host))throw new AppError("UNSAFE_FEED_URL",400,"Private IP feed hosts are not allowed.");}else{const addresses=await lookup(host,{all:true,verbatim:true});if(addresses.length===0||addresses.some((entry)=>privateIp(entry.address)))throw new AppError("UNSAFE_FEED_URL",400,"Feed host did not resolve to a safe public address.");}return url;}
async function fetchSafeText(input:string){let current=await assertSafeFeedUrl(input);for(let redirect=0;redirect<4;redirect+=1){const response=await fetch(current,{redirect:"manual",signal:AbortSignal.timeout(12_000),headers:{"user-agent":"ResearVia-Academic-Aggregator/0.1"}});if(response.status>=300&&response.status<400){const location=response.headers.get("location");if(!location)throw new AppError("FEED_REDIRECT_INVALID",502,"Feed returned an invalid redirect.");current=await assertSafeFeedUrl(new URL(location,current).toString());continue;}if(!response.ok)throw new AppError("FEED_FETCH_FAILED",502,`Feed request failed with status ${response.status}.`);const length=Number(response.headers.get("content-length")||0);if(length>MAX_FEED_BYTES)throw new AppError("FEED_TOO_LARGE",413,"Feed exceeds the 2 MB safety limit.");const text=await response.text();if(Buffer.byteLength(text,"utf8")>MAX_FEED_BYTES)throw new AppError("FEED_TOO_LARGE",413,"Feed exceeds the 2 MB safety limit.");return {text,contentType:response.headers.get("content-type")||""};}throw new AppError("FEED_REDIRECT_LIMIT",502,"Feed redirected too many times.");}
const arr=<T>(value:T|T[]|undefined):T[]=>value===undefined?[]:Array.isArray(value)?value:[value];
function textValue(value:unknown):string{if(typeof value==="string"||typeof value==="number")return String(value);if(value&&typeof value==="object"&&"#text" in value)return textValue((value as Record<string,unknown>)["#text"]);return "";}
function linkValue(value:unknown):string{if(typeof value==="string")return value;if(Array.isArray(value)){for(const item of value){const found:string=linkValue(item);if(found)return found;}return "";}if(value&&typeof value==="object"){const record=value as Record<string,unknown>;return textValue(record["@_href"]??record.href??record.url??record.link);}return "";}
function feedItems(text:string,format:string){const trimmed=text.trim();if(format==="JSON"||(format==="AUTO"&&(trimmed.startsWith("[")||trimmed.startsWith("{")))){const parsed=JSON.parse(trimmed) as unknown;if(Array.isArray(parsed))return parsed;if(parsed&&typeof parsed==="object"){const record=parsed as Record<string,unknown>;const candidate=record.items??record.results??record.data;return Array.isArray(candidate)?candidate:[];}return [];}const parsed=new XMLParser({ignoreAttributes:false,trimValues:true}).parse(text) as Record<string,unknown>;const rss=(parsed.rss as Record<string,unknown>|undefined)?.channel as Record<string,unknown>|undefined;if(rss)return arr(rss.item);const atom=parsed.feed as Record<string,unknown>|undefined;if(atom)return arr(atom.entry);return [];}
function slug(title:string,sourceUrl:string){const base=title.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,220)||"academic-item";return `${base}-${createHash("sha1").update(sourceUrl).digest("hex").slice(0,10)}`;}
function normalizeItem(raw:unknown,feedUrl:string){if(!raw||typeof raw!=="object")return null;const item=raw as Record<string,unknown>;const title=textValue(item.title??item.name).trim();if(!title)return null;const applicationUrl=linkValue(item.link??item.url??item.applicationUrl)||feedUrl;const description=textValue(item.description??item.summary??item.content??item.eligibility).replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,5000);const explicitDeadline=textValue(item.deadline).trim();const deadline=explicitDeadline&&!Number.isNaN(Date.parse(explicitDeadline))?new Date(explicitDeadline):null;return{title,applicationUrl,description,deadline};}
export async function listFeedSources(){await connectDatabase();return AcademicFeedSource.find().sort({updatedAt:-1}).lean();}
export async function createFeedSource(adminUserId:string,input:Record<string,unknown>){await assertSafeFeedUrl(String(input.url));await connectDatabase();return AcademicFeedSource.create({...input,createdBy:adminUserId});}
export async function deleteFeedSource(id:string){await connectDatabase();const r=await AcademicFeedSource.deleteOne({_id:id});if(!r.deletedCount)throw new AppError("FEED_SOURCE_NOT_FOUND",404,"Feed source not found.");}
export async function syncFeedSource(id:string){await connectDatabase();const source=await AcademicFeedSource.findById(id);if(!source)throw new AppError("FEED_SOURCE_NOT_FOUND",404,"Feed source not found.");if(!source.active)throw new AppError("FEED_SOURCE_DISABLED",400,"Feed source is disabled.");try{const fetched=await fetchSafeText(source.url);const rawItems=feedItems(fetched.text,source.format);let imported=0;for(const raw of rawItems.slice(0,250)){const item=normalizeItem(raw,source.url);if(!item)continue;const sourceUrl=item.applicationUrl;const common={country:source.defaultCountry,applicationUrl:item.applicationUrl,sourceUrl,retrievedAt:new Date(),lastVerifiedAt:null,status:"DRAFT" as const,source:"FEED" as const};if(source.entityType==="SCHOLARSHIP"){await Scholarship.findOneAndUpdate({source:"FEED",sourceUrl},{$set:{name:item.title,provider:source.defaultProvider,eligibility:item.description,deadline:item.deadline,...common},$setOnInsert:{slug:slug(item.title,sourceUrl)}},{upsert:true,new:true,runValidators:true});}else{await Opportunity.findOneAndUpdate({source:"FEED",sourceUrl},{$set:{title:item.title,type:source.defaultOpportunityType,organization:source.defaultProvider,description:item.description,deadline:item.deadline,...common},$setOnInsert:{slug:slug(item.title,sourceUrl)}},{upsert:true,new:true,runValidators:true});}imported+=1;}source.lastSyncedAt=new Date();source.lastError=null;await source.save();return{imported,totalSeen:rawItems.length,status:"DRAFT_REVIEW_REQUIRED" as const};}catch(error){source.lastError=(error instanceof Error?error.message:"Feed sync failed").slice(0,1000);await source.save();throw error;}}
